import type { Metadata } from "next";
import { poppins } from "@/utils/fonts";
import "./globals.css";
import { AppProvider } from "@/contexts/provider";
import { CookiesProvider } from 'next-client-cookies/server';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins}`}>
        <AppProvider>
          <CookiesProvider>
            {children}
          </CookiesProvider>
        </AppProvider>
      </body>
    </html>
  );
}
