version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./env.yaml
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multi
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - ./env.yaml
    environment:
      - DB_NAME = process.env.DB_DATABASE
      - DB_PORT = process.env.DB_PORT
      - DB_PASSWORD = process.env.DB_PASSWORD
      - DB_HOST = localhost
      - DB_USER = process.env.DB_USERNAME
      - DATABASE_URL = process.env.DB_URL
    volumes:
      - ./:/src
      - /node_modules
volumes:
  db:
    driver: local